### ISSUE TITLE
I got the "Thanks for using this app for over a week!" the day I installed the app

### ISSUE THREAD

**Issue by ordago** [CytoDev/FrequencyCalculator#3]

**Comment by cytodev** [comment]
I noticed that too when I reinstalled the app last week. I believe this has something to do with the way I calculate the install time. It seems newly installed applications don't have a date marking when they're first opened.

This is a very annoying issue to say the least. I would not want an application to ask for feedback or a rating when I first open in.

**Comment by ordago** [comment]
It wasn't the first time I opened the app for me. It appeared when I was trying to reproduce the disappearing home icon issue.

**Comment by cytodev** [comment]
That's interesting. Can you reproduce the issue by uninstalling and installing again? If you open the app and close it until it appears without changing the color of the icon, does it still pop up?

**Comment by ordago** [comment]
I don't know if this helps but if I go to _App info_ and _clear data_ and then open the app I get the message the first time it opens.

Just tried a fresh install and didn't get the message. I tried opening and closing several times and nothing. Swiping from recent and force stopping it and still nothing. Couln't make it trigger.

**Comment by cytodev** [comment]
@ordago That leads me to believe it defaults to calling the dialog when the value isn't set. However, that [shouldn't be the case](https://github.com/CytoDev/FrequencyCalculator/blob/master/app/src/main/java/io/cytodev/freqcalc/logic/DateChecker.java#L76-L88). Can you verify the [`Log.wtf`](https://github.com/CytoDev/FrequencyCalculator/blob/master/app/src/main/java/io/cytodev/freqcalc/logic/DateChecker.java#L85) is called?
