### ISSUE TITLE
Activating the "Themed icon" option deletes the shortcut on the home screen

### ISSUE THREAD

**Issue by ordago** [CytoDev/FrequencyCalculator#4]
I'm using a Moto G 2nd gen (XT1072), with the default launcher (Android 6.0)

**Comment by cytodev** [comment]
Does it keep the shortcut inside the launcher menu? I believe homescreen shortcuts are in a different category, so this should be an easy-ish fix.

**Comment by ordago** [comment]
Which was the launcher menu again? I get mixed up with the terms.

I see no problem with the icon in the drawer.

I added to shortcut to the home screen for easy access and noticed the issue.

**Comment by cytodev** [comment]
Drawer, my bad. I believe I know where to look now. I'll get an updated version up as soon as I test this idea through.

**Comment by ordago** [comment]
I just noticed it takes a (short) while for the old icon to disappear. While it is still there if I click on it I get a Toast saying _app isn't installed_.

**Comment by cytodev** [comment]
@ordago That's the expected behaviour. OS latency is not something I can fix with this app.

**Comment by cytodev** [comment]
@ordago After looking around for possible fixes to this issue I have come across none that are suitable. It does not seem to be possible to query the launcher activity which apps are on the home screen. And it would be very annoying to constantly find my app there after changing the icon.

For this reason, I am applying the wontfix label. Perhaps it will be possible in the future, but as of now I need to close this as unfixable without negative experience for user who did not put the app on their home screen.
