### ISSUE TITLE
[UX] [suggestion] App shows 0.0 for values below precision

### ISSUE THREAD

**Issue by ordago** [CytoDev/FrequencyCalculator#5]
If a user hasn't visited the settings yet he might not know the level of precision the app is using. Wouln't it be better if said something to let the user know. Perhaps 'value below precision point' serves the purpose, but it's long. Or maybe at least show 0 alone without the decimal point.

**Comment by cytodev** [comment]
A zero without the decimal point leads to believe the application is not accurate enough. I think it would be better to opt for a hint that points to the settings. This is harder to implement than a simple [toast](https://developer.android.com/guide/topics/ui/notifiers/toasts.html) or [snackbar](https://developer.android.com/reference/android/support/design/widget/Snackbar.html), but I believe this is somewhat more user friendly.

Perhaps a message like "below precision" can suffice as a snackbar along with a button reading "show more" can easily point the user to the right settings page.

@ordago What do you think?

**Comment by ordago** [comment]
> A zero without the decimal point leads to believe the application is not accurate enough.

I think 0.0 leads to believe the app is accurate and the result is exactly zero.

If you enter 6.000Hz both the seconds and minutes fields show "0.0". Because of having two fields with the same value I wouldn't opt for a Toast/Snackbar.

For those reasons I lean towards the text in the EditText field.

**Comment by ordago** [comment]
![suggestion2](https://cloud.githubusercontent.com/assets/6376814/16556878/6f19cf68-41d4-11e6-8182-4434a7a54365.png)

I think the current solution of using 0.001 as the default lowest value is not better than using 0.0 as before. I've atatched a screenshot with my proposed solution.

You know the math behind it, but there can be users who don't know better and don't think twice seeing the 0.001 value.
